#!/bin/sh

if [ "$1" = "--detached" ]; then
  shift
else
  [ -x "$0" ] || chmod +x "$0"
  "$0" --detached ${1+"$@"} &
  wait $!
  exit $?
fi

source /etc/preinit
script_init

getCmdLine(){
  dd status=none "if=$1" bs=64 count=8 skip=1 | tr -d '\0' | tr ' ' '\n'
  echo
}

memboot(){
  local bootimg="$1";shift
  [ -f "$bootimg" ] || return 1
  local cmdline="$(getCmdLine "$bootimg" | (grep -v "$modname-*shell"; echo "$@") | xargs)"
  echo "$0 $bootimg $cmdline"
  kexec -l -t zImage "$bootimg" "--command-line=$cmdline" --atags || return 1
  trap ":" HUP TERM
  killall -q clovershell
  uistop
  sync
  cd /
  umount -a -r 2>/dev/null
  disableUsbDevice
  kexec -e
  while :;do sleep 1;:;done
}

reboot_kexec(){
  local bootimg="$1"
  if [ -f "$bootimg" ]; then
    shift
  else
    bootimg="$temppath/boot.img"
    readBoot2 > "$bootimg" || return 1
  fi
  [ -f "$bootimg" ] || return 1
  memboot "$bootimg" ${1+"$@"}
}

clovershellActive(){
  [ "$cf_clovershell" = "y" ] && return 0
  (ps | grep -vF grep;pack_list) | grep -qF clovershell
}

recovery(){
  local bootimg="$1"
  [ -f "$bootimg" ] && shift || bootimg=""
  local rshell="$modname-shell"
  clovershellActive && rshell="$modname-clovershell"
  echo "$*" | grep -q "$modname-*shell" && rshell=""
  reboot_kexec "$bootimg" "$rshell" ${1+"$@"}
}

cdir="$(dirname "$(readlink -f "$0")")"
if [ -f "$cdir/kexec" ]; then
  [ -x "$cdir/kexec" ] || chmod +x "$cdir/kexec"
  export PATH="$cdir:$PATH"
fi
${1+"$@"}
