//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.clusterrr.hakchi_gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.clusterrr.hakchi_gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing games, please wait....
        /// </summary>
        internal static string AddingGames {
            get {
                return ResourceManager.GetString("AddingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data automatically filled for {0} game(s)..
        /// </summary>
        internal static string AutofillResult {
            get {
                return ResourceManager.GetString("AutofillResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Select+A/B for a second to enable/disable autofire A/B..
        /// </summary>
        internal static string AutofireHelp1 {
            get {
                return ResourceManager.GetString("AutofireHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_2600 {
            get {
                object obj = ResourceManager.GetObject("blank_2600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_32x {
            get {
                object obj = ResourceManager.GetObject("blank_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_app {
            get {
                object obj = ResourceManager.GetObject("blank_app", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_arcade {
            get {
                object obj = ResourceManager.GetObject("blank_arcade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_fds {
            get {
                object obj = ResourceManager.GetObject("blank_fds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_gb {
            get {
                object obj = ResourceManager.GetObject("blank_gb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_gba {
            get {
                object obj = ResourceManager.GetObject("blank_gba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_gbc {
            get {
                object obj = ResourceManager.GetObject("blank_gbc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_genesis {
            get {
                object obj = ResourceManager.GetObject("blank_genesis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_gg {
            get {
                object obj = ResourceManager.GetObject("blank_gg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_jp {
            get {
                object obj = ResourceManager.GetObject("blank_jp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_n64 {
            get {
                object obj = ResourceManager.GetObject("blank_n64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_neogeo {
            get {
                object obj = ResourceManager.GetObject("blank_neogeo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_nes {
            get {
                object obj = ResourceManager.GetObject("blank_nes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_pce {
            get {
                object obj = ResourceManager.GetObject("blank_pce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_sms {
            get {
                object obj = ResourceManager.GetObject("blank_sms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_snes_us {
            get {
                object obj = ResourceManager.GetObject("blank_snes_us", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building the custom kernel image....
        /// </summary>
        internal static string BuildingCustom {
            get {
                return ResourceManager.GetString("BuildingCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building the folder structure....
        /// </summary>
        internal static string BuildingFolders {
            get {
                return ResourceManager.GetString("BuildingFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom kernel.
        /// </summary>
        internal static string CustomKernel {
            get {
                return ResourceManager.GetString("CustomKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to flash the custom kernel?.
        /// </summary>
        internal static string CustomKernelQ {
            get {
                return ResourceManager.GetString("CustomKernelQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you need to flash the custom kernel to your NES Mini. This is only required once. Do you want to continue?.
        /// </summary>
        internal static string CustomWarning {
            get {
                return ResourceManager.GetString("CustomWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original 30 games.
        /// </summary>
        internal static string Default30games {
            get {
                return ResourceManager.GetString("Default30games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete &quot;{0}&quot;?.
        /// </summary>
        internal static string DeleteElement {
            get {
                return ResourceManager.GetString("DeleteElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete {0} elements?.
        /// </summary>
        internal static string DeleteElements {
            get {
                return ResourceManager.GetString("DeleteElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete &quot;{0}&quot; game?.
        /// </summary>
        internal static string DeleteGame {
            get {
                return ResourceManager.GetString("DeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the &quot;{0}&quot; preset?.
        /// </summary>
        internal static string DeletePreset {
            get {
                return ResourceManager.GetString("DeletePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.S. If you like it, you can donate to me. You can find my PayPal in the &quot;About&quot; box..
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! Wait until the power LED goes out and restart your NES Mini..
        /// </summary>
        internal static string DoneUploaded {
            get {
                return ResourceManager.GetString("DoneUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! You can upload games to your NES Mini now..
        /// </summary>
        internal static string DoneYouCanUpload {
            get {
                return ResourceManager.GetString("DoneYouCanUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading box art for all games (I&apos;m feeling lucky!).
        /// </summary>
        internal static string DownloadAllCoversTitle {
            get {
                return ResourceManager.GetString("DownloadAllCoversTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the current operation?.
        /// </summary>
        internal static string DoYouWantCancel {
            get {
                return ResourceManager.GetString("DoYouWantCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string DoYouWantToContinue {
            get {
                return ResourceManager.GetString("DoYouWantToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumping kernel....
        /// </summary>
        internal static string DumpingKernel {
            get {
                return ResourceManager.GetString("DumpingKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to dump the kernel?.
        /// </summary>
        internal static string DumpKernelQ {
            get {
                return ResourceManager.GetString("DumpKernelQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command:.
        /// </summary>
        internal static string ExecutingCommand {
            get {
                return ResourceManager.GetString("ExecutingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing fes1....
        /// </summary>
        internal static string ExecutingFes1 {
            get {
                return ResourceManager.GetString("ExecutingFes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add global command-line arguments which will be appended to all games including the original 30. This is only for experts!.
        /// </summary>
        internal static string ExtraArgsInfo {
            get {
                return ResourceManager.GetString("ExtraArgsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra command-line arguments.
        /// </summary>
        internal static string ExtraArgsTitle {
            get {
                return ResourceManager.GetString("ExtraArgsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello there! I&apos;m very glad that you are using hakchi2. It&apos;s very simple to use. Just click &quot;Add more games&quot;, select some ROMs, press &quot;Synchronize&quot; and follow the instructions. Good luck!.
        /// </summary>
        internal static string FirstRun {
            get {
                return ResourceManager.GetString("FirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashing custom kernel....
        /// </summary>
        internal static string FlasingCustom {
            get {
                return ResourceManager.GetString("FlasingCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashing original kernel....
        /// </summary>
        internal static string FlasingOriginal {
            get {
                return ResourceManager.GetString("FlasingOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_a {
            get {
                object obj = ResourceManager.GetObject("folder_a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_b {
            get {
                object obj = ResourceManager.GetObject("folder_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_back {
            get {
                object obj = ResourceManager.GetObject("folder_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_c {
            get {
                object obj = ResourceManager.GetObject("folder_c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_d {
            get {
                object obj = ResourceManager.GetObject("folder_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_e {
            get {
                object obj = ResourceManager.GetObject("folder_e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_f {
            get {
                object obj = ResourceManager.GetObject("folder_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_g {
            get {
                object obj = ResourceManager.GetObject("folder_g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_h {
            get {
                object obj = ResourceManager.GetObject("folder_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_i {
            get {
                object obj = ResourceManager.GetObject("folder_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_j {
            get {
                object obj = ResourceManager.GetObject("folder_j", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_k {
            get {
                object obj = ResourceManager.GetObject("folder_k", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_l {
            get {
                object obj = ResourceManager.GetObject("folder_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_m {
            get {
                object obj = ResourceManager.GetObject("folder_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_n {
            get {
                object obj = ResourceManager.GetObject("folder_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_number {
            get {
                object obj = ResourceManager.GetObject("folder_number", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_o {
            get {
                object obj = ResourceManager.GetObject("folder_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_p {
            get {
                object obj = ResourceManager.GetObject("folder_p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_q {
            get {
                object obj = ResourceManager.GetObject("folder_q", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_r {
            get {
                object obj = ResourceManager.GetObject("folder_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_s {
            get {
                object obj = ResourceManager.GetObject("folder_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_t {
            get {
                object obj = ResourceManager.GetObject("folder_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_u {
            get {
                object obj = ResourceManager.GetObject("folder_u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_v {
            get {
                object obj = ResourceManager.GetObject("folder_v", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_w {
            get {
                object obj = ResourceManager.GetObject("folder_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_x {
            get {
                object obj = ResourceManager.GetObject("folder_x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_y {
            get {
                object obj = ResourceManager.GetObject("folder_y", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_z {
            get {
                object obj = ResourceManager.GetObject("folder_z", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted content will be moved to the Recycle Bin. You can delete this folder permanently or move the games to other folders..
        /// </summary>
        internal static string FolderContent {
            get {
                return ResourceManager.GetString("FolderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string FolderNameBack {
            get {
                return ResourceManager.GetString("FolderNameBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More games....
        /// </summary>
        internal static string FolderNameMoreGames {
            get {
                return ResourceManager.GetString("FolderNameMoreGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        internal static string FolderNameNewFolder {
            get {
                return ResourceManager.GetString("FolderNameNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original 30 games.
        /// </summary>
        internal static string FolderNameOriginalGames {
            get {
                return ResourceManager.GetString("FolderNameOriginalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle Bin.
        /// </summary>
        internal static string FolderNameTrashBin {
            get {
                return ResourceManager.GetString("FolderNameTrashBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsorted.
        /// </summary>
        internal static string FolderNameUnsorted {
            get {
                return ResourceManager.GetString("FolderNameUnsorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save this folder structure?.
        /// </summary>
        internal static string FoldersSaveQ {
            get {
                return ResourceManager.GetString("FoldersSaveQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; contains {1} elements..
        /// </summary>
        internal static string FolderStatistics {
            get {
                return ResourceManager.GetString("FolderStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, {0} uses four-screen mode (i.e. the game has additional VRAM memory in the cartridge), and this feature is not supported by the NES Mini. The game will probably not start. But it should work if other emulator&apos;s module installed. Do you want to add this game anyway?.
        /// </summary>
        internal static string FourScreenNotSupported {
            get {
                return ResourceManager.GetString("FourScreenNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Game Genie code &quot;{0}&quot; for game &quot;{1}&quot;..
        /// </summary>
        internal static string GameGenieFormatError {
            get {
                return ResourceManager.GetString("GameGenieFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t apply Game Genie code &quot;{0}&quot; to game &quot;{1}&quot; - value not found. Maybe this code is for another game?.
        /// </summary>
        internal static string GameGenieNotFound {
            get {
                return ResourceManager.GetString("GameGenieNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gamepad {
            get {
                object obj = ResourceManager.GetObject("gamepad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to games(s) selected.
        /// </summary>
        internal static string GamesSelected {
            get {
                return ResourceManager.GetString("GamesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, game &quot;{0}&quot; is too big..
        /// </summary>
        internal static string GameTooBig {
            get {
                return ResourceManager.GetString("GameTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete &quot;{0}&quot; code?.
        /// </summary>
        internal static string GGCodeDelete {
            get {
                return ResourceManager.GetString("GGCodeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a code!.
        /// </summary>
        internal static string GGCodeEmpty {
            get {
                return ResourceManager.GetString("GGCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code already exists. Do you want to edit it?.
        /// </summary>
        internal static string GGCodeExists {
            get {
                return ResourceManager.GetString("GGCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a description!.
        /// </summary>
        internal static string GGDescriptionEmpty {
            get {
                return ResourceManager.GetString("GGDescriptionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Googling for .
        /// </summary>
        internal static string GooglingFor {
            get {
                return ResourceManager.GetString("GooglingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green {
            get {
                object obj = ResourceManager.GetObject("green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a preset name for the current games selection..
        /// </summary>
        internal static string InputPreset {
            get {
                return ResourceManager.GetString("InputPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing mods....
        /// </summary>
        internal static string InstallingMods {
            get {
                return ResourceManager.GetString("InstallingMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid kernel header..
        /// </summary>
        internal static string InvalidKernelHeader {
            get {
                return ResourceManager.GetString("InvalidKernelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid kernel size:.
        /// </summary>
        internal static string InvalidKernelSize {
            get {
                return ResourceManager.GetString("InvalidKernelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your original kernel is saved in the &quot;dump&quot; folder. Do not lose it. .
        /// </summary>
        internal static string KernelDumped {
            get {
                return ResourceManager.GetString("KernelDumped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading games....
        /// </summary>
        internal static string LoadingGames {
            get {
                return ResourceManager.GetString("LoadingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME Menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, &quot;{0}&quot; uses mapper #{1} but this mapper is not supported by the NES Mini and the game will probably not start with the default emulator. But it should work if other emulator&apos;s module installed. Do you want to add this game?.
        /// </summary>
        internal static string MapperNotSupported {
            get {
                return ResourceManager.GetString("MapperNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel dumped but the MD5 checksum is unknown:.
        /// </summary>
        internal static string MD5Failed {
            get {
                return ResourceManager.GetString("MD5Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The kernel is already patched or it&apos;s an unknown revision. Please send this message to me (press Ctrl+C). Continue at your own risk..
        /// </summary>
        internal static string MD5Failed2 {
            get {
                return ResourceManager.GetString("MD5Failed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there are {0}MBytes of games, it&apos;s too much..
        /// </summary>
        internal static string MemoryFull {
            get {
                return ResourceManager.GetString("MemoryFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New games are moved to the &quot;Unsorted&quot; folder..
        /// </summary>
        internal static string NewGamesUnsorted {
            get {
                return ResourceManager.GetString("NewGamesUnsorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New selection preset.
        /// </summary>
        internal static string NewPreset {
            get {
                return ResourceManager.GetString("NewPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No for all.
        /// </summary>
        internal static string NoForAll {
            get {
                return ResourceManager.GetString("NoForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No kernel dump found.
        /// </summary>
        internal static string NoKernel {
            get {
                return ResourceManager.GetString("NoKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, dump the kernel image of your NES Mini. You only need to do this once. Do you want to continue?.
        /// </summary>
        internal static string NoKernelWarning {
            get {
                return ResourceManager.GetString("NoKernelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No kernel dump found. You need to dump the kernel first..
        /// </summary>
        internal static string NoKernelYouNeed {
            get {
                return ResourceManager.GetString("NoKernelYouNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found:.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to flash the original kernel?.
        /// </summary>
        internal static string OriginalKernelQ {
            get {
                return ResourceManager.GetString("OriginalKernelQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t worry! Everything is fine. There are just too many ROMs to transfer at once. Please wait until power LED goes out, press OK and follow the instructions to continue..
        /// </summary>
        internal static string ParticallyBody {
            get {
                return ResourceManager.GetString("ParticallyBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many ROMs.
        /// </summary>
        internal static string ParticallyTitle {
            get {
                return ResourceManager.GetString("ParticallyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch available.
        /// </summary>
        internal static string PatchAvailable {
            get {
                return ResourceManager.GetString("PatchAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is patch for &quot;{0}&quot;. Do you want to patch this game?.
        /// </summary>
        internal static string PatchQ {
            get {
                return ResourceManager.GetString("PatchQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this problem persists, try using another USB port or cable..
        /// </summary>
        internal static string PleaseTryAgainUSB {
            get {
                return ResourceManager.GetString("PleaseTryAgainUSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press OK to continue..
        /// </summary>
        internal static string PressOkToContinue {
            get {
                return ResourceManager.GetString("PressOkToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red {
            get {
                object obj = ResourceManager.GetObject("red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have the kernel dump. If you REALLY want to replace the backup of your kernel and you REALLY understand what you are doing, delete the &quot;dump&quot; folder manually..
        /// </summary>
        internal static string ReplaceKernelQ {
            get {
                return ResourceManager.GetString("ReplaceKernelQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one game..
        /// </summary>
        internal static string SelectAtLeast {
            get {
                return ResourceManager.GetString("SelectAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least two buttons..
        /// </summary>
        internal static string SelectAtLeastTwo {
            get {
                return ResourceManager.GetString("SelectAtLeastTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the modules to install on your NES Mini..
        /// </summary>
        internal static string SelectModsInstall {
            get {
                return ResourceManager.GetString("SelectModsInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the modules to remove from your NES Mini..
        /// </summary>
        internal static string SelectModsUninstall {
            get {
                return ResourceManager.GetString("SelectModsUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t forget to perform a factory reset if you want to delete all Suspend Points..
        /// </summary>
        internal static string UninstallFactoryNote {
            get {
                return ResourceManager.GetString("UninstallFactoryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        internal static string Uninstalling {
            get {
                return ResourceManager.GetString("Uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling mods....
        /// </summary>
        internal static string UninstallingMods {
            get {
                return ResourceManager.GetString("UninstallingMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove all traces of hakchi2 and return your NES Mini to its original state?.
        /// </summary>
        internal static string UninstallQ1 {
            get {
                return ResourceManager.GetString("UninstallQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done. Wait until the power LED goes out. You also need to flash the original kernel. Do you want to flash the original kernel now?.
        /// </summary>
        internal static string UninstallQ2 {
            get {
                return ResourceManager.GetString("UninstallQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading new config....
        /// </summary>
        internal static string UploadingConfig {
            get {
                return ResourceManager.GetString("UploadingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading and running FES-1....
        /// </summary>
        internal static string UploadingFes1 {
            get {
                return ResourceManager.GetString("UploadingFes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading games....
        /// </summary>
        internal static string UploadingGames {
            get {
                return ResourceManager.GetString("UploadingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading the kernel....
        /// </summary>
        internal static string UploadingKernel {
            get {
                return ResourceManager.GetString("UploadingKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing original games....
        /// </summary>
        internal static string UploadingOriginalGames {
            get {
                return ResourceManager.GetString("UploadingOriginalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify failed :O This is not good..
        /// </summary>
        internal static string VerifyFailed {
            get {
                return ResourceManager.GetString("VerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying....
        /// </summary>
        internal static string Verifying {
            get {
                return ResourceManager.GetString("Verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the device....
        /// </summary>
        internal static string WaitingForDevice {
            get {
                return ResourceManager.GetString("WaitingForDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow.
        /// </summary>
        internal static string Wow {
            get {
                return ResourceManager.GetString("Wow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the Zadig utility to install the driver on Windows XP/2000..
        /// </summary>
        internal static string XpZadig {
            get {
                return ResourceManager.GetString("XpZadig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes for all.
        /// </summary>
        internal static string YesForAll {
            get {
                return ResourceManager.GetString("YesForAll", resourceCulture);
            }
        }
    }
}
