//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.clusterrr.hakchi_gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.clusterrr.hakchi_gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building the custom kernel image....
        /// </summary>
        internal static string BuildingCustom {
            get {
                return ResourceManager.GetString("BuildingCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom kernel.
        /// </summary>
        internal static string CustomKernel {
            get {
                return ResourceManager.GetString("CustomKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to flash the custom kernel?.
        /// </summary>
        internal static string CustomKernelQ {
            get {
                return ResourceManager.GetString("CustomKernelQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you need to flash the custom kernel to your NES Mini. This is also required only once. Do you want to continue?.
        /// </summary>
        internal static string CustomWarning {
            get {
                return ResourceManager.GetString("CustomWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original 30 games.
        /// </summary>
        internal static string Default30games {
            get {
                return ResourceManager.GetString("Default30games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete &quot;{0}&quot; preset?.
        /// </summary>
        internal static string DeletePreset {
            get {
                return ResourceManager.GetString("DeletePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}?.
        /// </summary>
        internal static string DeleteQ {
            get {
                return ResourceManager.GetString("DeleteQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.S. If you like it you can donate me. You can find my PayPal into the &quot;About&quot; box..
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! Wait until the power led goes out and restart your NES Mini..
        /// </summary>
        internal static string DoneUploaded {
            get {
                return ResourceManager.GetString("DoneUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! You can upload games to your NES Mini now..
        /// </summary>
        internal static string DoneYouCanUpload {
            get {
                return ResourceManager.GetString("DoneYouCanUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the current operation?.
        /// </summary>
        internal static string DoYouWantCancel {
            get {
                return ResourceManager.GetString("DoYouWantCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string DoYouWantToContinue {
            get {
                return ResourceManager.GetString("DoYouWantToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumping kernel....
        /// </summary>
        internal static string DumpingKernel {
            get {
                return ResourceManager.GetString("DumpingKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to dump the kernel?.
        /// </summary>
        internal static string DumpKernelQ {
            get {
                return ResourceManager.GetString("DumpKernelQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command:.
        /// </summary>
        internal static string ExecutingCommand {
            get {
                return ResourceManager.GetString("ExecutingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing fes1....
        /// </summary>
        internal static string ExecutingFel1 {
            get {
                return ResourceManager.GetString("ExecutingFel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fes1 {
            get {
                object obj = ResourceManager.GetObject("fes1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello there! I&apos;m very glad that you are using my application. It&apos;s very simple to use. Just click &quot;Add more games&quot;, select some ROMs, press &quot;Synchronize&quot; and follow the instructions. Good luck!.
        /// </summary>
        internal static string FirstRun {
            get {
                return ResourceManager.GetString("FirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashing custom kernel....
        /// </summary>
        internal static string FlasingCustom {
            get {
                return ResourceManager.GetString("FlasingCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashing original kernel....
        /// </summary>
        internal static string FlasingOriginal {
            get {
                return ResourceManager.GetString("FlasingOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, {0} uses four-screen mode (i.e.  it&apos;s rare case the game has additional VRAM memory in cartridge) and this feature is not supported by NES Mini. Game probably will not start. Do you want to add this game anyway?.
        /// </summary>
        internal static string FourScreenNotSupported {
            get {
                return ResourceManager.GetString("FourScreenNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to games(s) selected.
        /// </summary>
        internal static string GamesSelected {
            get {
                return ResourceManager.GetString("GamesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input preset name for current games selection..
        /// </summary>
        internal static string InputPreset {
            get {
                return ResourceManager.GetString("InputPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid kernel header..
        /// </summary>
        internal static string InvalidKernelHeader {
            get {
                return ResourceManager.GetString("InvalidKernelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid kernel size:.
        /// </summary>
        internal static string InvalidKernelSize {
            get {
                return ResourceManager.GetString("InvalidKernelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your original kernel saved in the &quot;dump&quot; folder. It&apos;s better not to lose it. .
        /// </summary>
        internal static string KernelDumped {
            get {
                return ResourceManager.GetString("KernelDumped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NES Mini can handle only 97 games but you selected {0} games.  Do you want to continue?.
        /// </summary>
        internal static string ManyGames {
            get {
                return ResourceManager.GetString("ManyGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, {0} uses mapper #{1} but this mapper is not supported by NES Mini and game probably will not start. Do you want to add this game anyway?.
        /// </summary>
        internal static string MapperNotSupported {
            get {
                return ResourceManager.GetString("MapperNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel dumped but MD5 checksum is unknown:.
        /// </summary>
        internal static string MD5Failed {
            get {
                return ResourceManager.GetString("MD5Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe the kernel already patched or it&apos;s unknown revision. Please send this message to me (press Ctrl+C). Continue on your own risk..
        /// </summary>
        internal static string MD5Failed2 {
            get {
                return ResourceManager.GetString("MD5Failed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;database version=&quot;1.0&quot; conformance=&quot;strict&quot; agent=&quot;NesCartDB&quot; author=&quot;BootGod&quot; timestamp=&quot;Sat Aug 20 20:34:07 2016
        ///&quot;&gt;
        ///	&lt;game name=&quot;&amp;apos;89 Dennou Kyuusei Uranai&quot; altname=&quot;神宮館’８９電脳九星占い&quot; class=&quot;Licensed&quot; catalog=&quot;IPC-J1-01&quot; publisher=&quot;Jingukan&quot; developer=&quot;Micronics / Khaos&quot; region=&quot;Japan&quot; players=&quot;1&quot; date=&quot;1988-12-10&quot;&gt;
        ///		&lt;cartridge system=&quot;Famicom&quot; crc=&quot;BA58ED29&quot; sha1=&quot;56FE858D1035DCE4B68520F457A0858BAE7BB16D&quot; dump=&quot;ok&quot; dumper=&quot;bootgod&quot; datedumped=&quot;2007-11-11&quot;&gt;
        ///			&lt;bo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nescarts {
            get {
                return ResourceManager.GetString("nescarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New selection preset.
        /// </summary>
        internal static string NewPreset {
            get {
                return ResourceManager.GetString("NewPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No kernel dump found.
        /// </summary>
        internal static string NoKernel {
            get {
                return ResourceManager.GetString("NoKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First of all you need to dump the kernel image of your NES Mini. You need to do it only once. Do you want to continue?.
        /// </summary>
        internal static string NoKernelWarning {
            get {
                return ResourceManager.GetString("NoKernelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No kernel dump found. You need to dump kernel first..
        /// </summary>
        internal static string NoKernelYouNeed {
            get {
                return ResourceManager.GetString("NoKernelYouNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to flash the original kernel?.
        /// </summary>
        internal static string OriginalKernelQ {
            get {
                return ResourceManager.GetString("OriginalKernelQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again..
        /// </summary>
        internal static string PleaseTryAgain {
            get {
                return ResourceManager.GetString("PleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this problem repeats try to use another USB port or another USB cable..
        /// </summary>
        internal static string PleaseTryAgainUSB {
            get {
                return ResourceManager.GetString("PleaseTryAgainUSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press OK to continue..
        /// </summary>
        internal static string PressOkToContinue {
            get {
                return ResourceManager.GetString("PressOkToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have the kernel dump. If you REALLY want to replace buckup of you kernel and you REALLY understand what you are doing delete &quot;dump&quot; folder manually..
        /// </summary>
        internal static string ReplaceKernelQ {
            get {
                return ResourceManager.GetString("ReplaceKernelQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select at least one game..
        /// </summary>
        internal static string SelectAtLeast {
            get {
                return ResourceManager.GetString("SelectAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] uboot {
            get {
                object obj = ResourceManager.GetObject("uboot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t forget to do reset to factory settings if you want to delete all savestates..
        /// </summary>
        internal static string UninstallFactoryNote {
            get {
                return ResourceManager.GetString("UninstallFactoryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        internal static string Uninstalling {
            get {
                return ResourceManager.GetString("Uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to clean all traces of hakchi2 and return your NES Mini to original state?.
        /// </summary>
        internal static string UninstallQ1 {
            get {
                return ResourceManager.GetString("UninstallQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done. Wait until the power led goes out. Also you need to flash original kernel. Do you want to flash original kernel now?.
        /// </summary>
        internal static string UninstallQ2 {
            get {
                return ResourceManager.GetString("UninstallQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading and running fes1....
        /// </summary>
        internal static string UploadingFes1 {
            get {
                return ResourceManager.GetString("UploadingFes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading games....
        /// </summary>
        internal static string UploadingGames {
            get {
                return ResourceManager.GetString("UploadingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading the kernel....
        /// </summary>
        internal static string UploadingKernel {
            get {
                return ResourceManager.GetString("UploadingKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify failed :O This is no good..
        /// </summary>
        internal static string VerifyFailed {
            get {
                return ResourceManager.GetString("VerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying....
        /// </summary>
        internal static string Verifying {
            get {
                return ResourceManager.GetString("Verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the device....
        /// </summary>
        internal static string WaitingForDevice {
            get {
                return ResourceManager.GetString("WaitingForDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow.
        /// </summary>
        internal static string Wow {
            get {
                return ResourceManager.GetString("Wow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use Zadig util to install driver on Windows XP/2000..
        /// </summary>
        internal static string XpZadig {
            get {
                return ResourceManager.GetString("XpZadig", resourceCulture);
            }
        }
    }
}
