//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.clusterrr.hakchi_gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.clusterrr.hakchi_gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data automatically filled for {0} games..
        /// </summary>
        internal static string AutofillResult {
            get {
                return ResourceManager.GetString("AutofillResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Select+A/B for a second to enable/disable autofire for A/B..
        /// </summary>
        internal static string AutofireHelp1 {
            get {
                return ResourceManager.GetString("AutofireHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also X/Y buttons on Classic Controller will act as autofire A/B..
        /// </summary>
        internal static string AutofireHelp2 {
            get {
                return ResourceManager.GetString("AutofireHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_fds {
            get {
                object obj = ResourceManager.GetObject("blank_fds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_jp {
            get {
                object obj = ResourceManager.GetObject("blank_jp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building the custom kernel image....
        /// </summary>
        internal static string BuildingCustom {
            get {
                return ResourceManager.GetString("BuildingCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building folder structure....
        /// </summary>
        internal static string BuildingFolders {
            get {
                return ResourceManager.GetString("BuildingFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom kernel.
        /// </summary>
        internal static string CustomKernel {
            get {
                return ResourceManager.GetString("CustomKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to flash the custom kernel?.
        /// </summary>
        internal static string CustomKernelQ {
            get {
                return ResourceManager.GetString("CustomKernelQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you need to flash the custom kernel to your NES Mini. This is also required only once. Do you want to continue?.
        /// </summary>
        internal static string CustomWarning {
            get {
                return ResourceManager.GetString("CustomWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original 30 games.
        /// </summary>
        internal static string Default30games {
            get {
                return ResourceManager.GetString("Default30games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &quot;{0}&quot; folder?.
        /// </summary>
        internal static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete &quot;{0}&quot; preset?.
        /// </summary>
        internal static string DeletePreset {
            get {
                return ResourceManager.GetString("DeletePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}?.
        /// </summary>
        internal static string DeleteQ {
            get {
                return ResourceManager.GetString("DeleteQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.S. If you like it you can donate me. You can find my PayPal into the &quot;About&quot; box..
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! Wait until the power led goes out and restart your NES Mini..
        /// </summary>
        internal static string DoneUploaded {
            get {
                return ResourceManager.GetString("DoneUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! You can upload games to your NES Mini now..
        /// </summary>
        internal static string DoneYouCanUpload {
            get {
                return ResourceManager.GetString("DoneYouCanUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading covers for all games (I&apos;m feeling lucky!).
        /// </summary>
        internal static string DownloadAllCoversTitle {
            get {
                return ResourceManager.GetString("DownloadAllCoversTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the current operation?.
        /// </summary>
        internal static string DoYouWantCancel {
            get {
                return ResourceManager.GetString("DoYouWantCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string DoYouWantToContinue {
            get {
                return ResourceManager.GetString("DoYouWantToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumping kernel....
        /// </summary>
        internal static string DumpingKernel {
            get {
                return ResourceManager.GetString("DumpingKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to dump the kernel?.
        /// </summary>
        internal static string DumpKernelQ {
            get {
                return ResourceManager.GetString("DumpKernelQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command:.
        /// </summary>
        internal static string ExecutingCommand {
            get {
                return ResourceManager.GetString("ExecutingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing fes1....
        /// </summary>
        internal static string ExecutingFel1 {
            get {
                return ResourceManager.GetString("ExecutingFel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add some global command line arguments which will be appended to all games including original ones. It&apos;s only for experts!.
        /// </summary>
        internal static string ExtraArgsInfo {
            get {
                return ResourceManager.GetString("ExtraArgsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra command line arguments.
        /// </summary>
        internal static string ExtraArgsTitle {
            get {
                return ResourceManager.GetString("ExtraArgsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello there! I&apos;m very glad that you are using my application. It&apos;s very simple to use. Just click &quot;Add more games&quot;, select some ROMs, press &quot;Synchronize&quot; and follow the instructions. Good luck!.
        /// </summary>
        internal static string FirstRun {
            get {
                return ResourceManager.GetString("FirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashing custom kernel....
        /// </summary>
        internal static string FlasingCustom {
            get {
                return ResourceManager.GetString("FlasingCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashing original kernel....
        /// </summary>
        internal static string FlasingOriginal {
            get {
                return ResourceManager.GetString("FlasingOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_a {
            get {
                object obj = ResourceManager.GetObject("folder_a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_b {
            get {
                object obj = ResourceManager.GetObject("folder_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_back {
            get {
                object obj = ResourceManager.GetObject("folder_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_c {
            get {
                object obj = ResourceManager.GetObject("folder_c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_d {
            get {
                object obj = ResourceManager.GetObject("folder_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_e {
            get {
                object obj = ResourceManager.GetObject("folder_e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_f {
            get {
                object obj = ResourceManager.GetObject("folder_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_g {
            get {
                object obj = ResourceManager.GetObject("folder_g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_h {
            get {
                object obj = ResourceManager.GetObject("folder_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_i {
            get {
                object obj = ResourceManager.GetObject("folder_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_j {
            get {
                object obj = ResourceManager.GetObject("folder_j", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_k {
            get {
                object obj = ResourceManager.GetObject("folder_k", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_l {
            get {
                object obj = ResourceManager.GetObject("folder_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_m {
            get {
                object obj = ResourceManager.GetObject("folder_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_n {
            get {
                object obj = ResourceManager.GetObject("folder_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_number {
            get {
                object obj = ResourceManager.GetObject("folder_number", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_o {
            get {
                object obj = ResourceManager.GetObject("folder_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_p {
            get {
                object obj = ResourceManager.GetObject("folder_p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_q {
            get {
                object obj = ResourceManager.GetObject("folder_q", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_r {
            get {
                object obj = ResourceManager.GetObject("folder_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_s {
            get {
                object obj = ResourceManager.GetObject("folder_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_t {
            get {
                object obj = ResourceManager.GetObject("folder_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_u {
            get {
                object obj = ResourceManager.GetObject("folder_u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_v {
            get {
                object obj = ResourceManager.GetObject("folder_v", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_w {
            get {
                object obj = ResourceManager.GetObject("folder_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_x {
            get {
                object obj = ResourceManager.GetObject("folder_x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_y {
            get {
                object obj = ResourceManager.GetObject("folder_y", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_z {
            get {
                object obj = ResourceManager.GetObject("folder_z", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder content will be moved to &quot;Unsorted&quot; folder..
        /// </summary>
        internal static string FolderContent {
            get {
                return ResourceManager.GetString("FolderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;- Back.
        /// </summary>
        internal static string FolderNameBack {
            get {
                return ResourceManager.GetString("FolderNameBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More games....
        /// </summary>
        internal static string FolderNameMoreGames {
            get {
                return ResourceManager.GetString("FolderNameMoreGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;- Original games.
        /// </summary>
        internal static string FolderNameOriginalGames {
            get {
                return ResourceManager.GetString("FolderNameOriginalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, {0} uses four-screen mode (i.e.  it&apos;s rare case the game has additional VRAM memory in cartridge) and this feature is not supported by NES Mini. Game probably will not start. Do you want to add this game anyway?.
        /// </summary>
        internal static string FourScreenNotSupported {
            get {
                return ResourceManager.GetString("FourScreenNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Game Ganie code &quot;{0}&quot; for game &quot;{1}&quot;..
        /// </summary>
        internal static string GameGenieFormatError {
            get {
                return ResourceManager.GetString("GameGenieFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t apply Game Genie code &quot;{0}&quot; to game &quot;{1}&quot; -  value not found. Maybe this code for other game?.
        /// </summary>
        internal static string GameGenieNotFound {
            get {
                return ResourceManager.GetString("GameGenieNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gamepad {
            get {
                object obj = ResourceManager.GetObject("gamepad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to games(s) selected.
        /// </summary>
        internal static string GamesSelected {
            get {
                return ResourceManager.GetString("GamesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete &quot;{0}&quot; code?.
        /// </summary>
        internal static string GGCodeDelete {
            get {
                return ResourceManager.GetString("GGCodeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a code!.
        /// </summary>
        internal static string GGCodeEmpty {
            get {
                return ResourceManager.GetString("GGCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code already exist. Do you want to edit it?.
        /// </summary>
        internal static string GGCodeExists {
            get {
                return ResourceManager.GetString("GGCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a description!.
        /// </summary>
        internal static string GGDescriptionEmpty {
            get {
                return ResourceManager.GetString("GGDescriptionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Googling for .
        /// </summary>
        internal static string GooglingFor {
            get {
                return ResourceManager.GetString("GooglingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input preset name for current games selection..
        /// </summary>
        internal static string InputPreset {
            get {
                return ResourceManager.GetString("InputPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid kernel header..
        /// </summary>
        internal static string InvalidKernelHeader {
            get {
                return ResourceManager.GetString("InvalidKernelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid kernel size:.
        /// </summary>
        internal static string InvalidKernelSize {
            get {
                return ResourceManager.GetString("InvalidKernelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your original kernel saved in the &quot;dump&quot; folder. It&apos;s better not to lose it. .
        /// </summary>
        internal static string KernelDumped {
            get {
                return ResourceManager.GetString("KernelDumped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading games....
        /// </summary>
        internal static string LoadingGames {
            get {
                return ResourceManager.GetString("LoadingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, {0} uses mapper #{1} but this mapper is not supported by NES Mini and game probably will not start. Do you want to add this game anyway?.
        /// </summary>
        internal static string MapperNotSupported {
            get {
                return ResourceManager.GetString("MapperNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel dumped but MD5 checksum is unknown:.
        /// </summary>
        internal static string MD5Failed {
            get {
                return ResourceManager.GetString("MD5Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe the kernel already patched or it&apos;s unknown revision. Please send this message to me (press Ctrl+C). Continue on your own risk..
        /// </summary>
        internal static string MD5Failed2 {
            get {
                return ResourceManager.GetString("MD5Failed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New selection preset.
        /// </summary>
        internal static string NewPreset {
            get {
                return ResourceManager.GetString("NewPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No for all.
        /// </summary>
        internal static string NoForAll {
            get {
                return ResourceManager.GetString("NoForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No kernel dump found.
        /// </summary>
        internal static string NoKernel {
            get {
                return ResourceManager.GetString("NoKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First of all you need to dump the kernel image of your NES Mini. You need to do it only once. Do you want to continue?.
        /// </summary>
        internal static string NoKernelWarning {
            get {
                return ResourceManager.GetString("NoKernelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No kernel dump found. You need to dump kernel first..
        /// </summary>
        internal static string NoKernelYouNeed {
            get {
                return ResourceManager.GetString("NoKernelYouNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found:.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to flash the original kernel?.
        /// </summary>
        internal static string OriginalKernelQ {
            get {
                return ResourceManager.GetString("OriginalKernelQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t worry! Everything is fine. Just there are too many ROMs to tranfer them at once. Please wait until power led goes out, press OK and follow instructions to continue..
        /// </summary>
        internal static string ParticallyBody {
            get {
                return ResourceManager.GetString("ParticallyBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many ROMs.
        /// </summary>
        internal static string ParticallyTitle {
            get {
                return ResourceManager.GetString("ParticallyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch available.
        /// </summary>
        internal static string PatchAvailable {
            get {
                return ResourceManager.GetString("PatchAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is patch for &quot;{0}&quot;. Do you want to patch this game?.
        /// </summary>
        internal static string PatchQ {
            get {
                return ResourceManager.GetString("PatchQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this problem repeats try to use another USB port or another USB cable..
        /// </summary>
        internal static string PleaseTryAgainUSB {
            get {
                return ResourceManager.GetString("PleaseTryAgainUSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press OK to continue..
        /// </summary>
        internal static string PressOkToContinue {
            get {
                return ResourceManager.GetString("PressOkToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have the kernel dump. If you REALLY want to replace buckup of you kernel and you REALLY understand what you are doing delete &quot;dump&quot; folder manually..
        /// </summary>
        internal static string ReplaceKernelQ {
            get {
                return ResourceManager.GetString("ReplaceKernelQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select at least one game..
        /// </summary>
        internal static string SelectAtLeast {
            get {
                return ResourceManager.GetString("SelectAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select at least two buttons..
        /// </summary>
        internal static string SelectAtLeastTwo {
            get {
                return ResourceManager.GetString("SelectAtLeastTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t forget to do reset to factory settings if you want to delete all savestates..
        /// </summary>
        internal static string UninstallFactoryNote {
            get {
                return ResourceManager.GetString("UninstallFactoryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        internal static string Uninstalling {
            get {
                return ResourceManager.GetString("Uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to clean all traces of hakchi2 and return your NES Mini to original state?.
        /// </summary>
        internal static string UninstallQ1 {
            get {
                return ResourceManager.GetString("UninstallQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done. Wait until the power led goes out. Also you need to flash original kernel. Do you want to flash original kernel now?.
        /// </summary>
        internal static string UninstallQ2 {
            get {
                return ResourceManager.GetString("UninstallQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading and running fes1....
        /// </summary>
        internal static string UploadingFes1 {
            get {
                return ResourceManager.GetString("UploadingFes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading games....
        /// </summary>
        internal static string UploadingGames {
            get {
                return ResourceManager.GetString("UploadingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading the kernel....
        /// </summary>
        internal static string UploadingKernel {
            get {
                return ResourceManager.GetString("UploadingKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify failed :O This is no good..
        /// </summary>
        internal static string VerifyFailed {
            get {
                return ResourceManager.GetString("VerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying....
        /// </summary>
        internal static string Verifying {
            get {
                return ResourceManager.GetString("Verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the device....
        /// </summary>
        internal static string WaitingForDevice {
            get {
                return ResourceManager.GetString("WaitingForDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow.
        /// </summary>
        internal static string Wow {
            get {
                return ResourceManager.GetString("Wow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use Zadig util to install driver on Windows XP/2000..
        /// </summary>
        internal static string XpZadig {
            get {
                return ResourceManager.GetString("XpZadig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes for all.
        /// </summary>
        internal static string YesForAll {
            get {
                return ResourceManager.GetString("YesForAll", resourceCulture);
            }
        }
    }
}
