#!/bin/sh
source /etc/preinit
script_init

CLV_BOARD_NAME="$(cat "/etc/clover/boardtype")"
MODULE="clvcon"
[ -f "/lib/modules/$(uname -r)/extra/$MODULE.ko" ] || MODULE="clovercon"

start(){
  [ -z "$cfg_clovercon_enabled" ] && cfg_clovercon_enabled='y'
  [ -z "$cfg_clovercon_home_combination" ] && cfg_clovercon_home_combination='0x24'
  [ -z "$cfg_clovercon_autofire" ] && cfg_clovercon_autofire='1'
  [ -z "$cfg_clovercon_autofire_xy" ] && cfg_clovercon_autofire_xy='0'
  [ -z "$cfg_clovercon_autofire_interval" ] && cfg_clovercon_autofire_interval='8'
  [ -z "$cfg_clovercon_fc_start" ] && cfg_clovercon_fc_start='0'
  save_config
  [ "$cfg_clovercon_enabled"="y" ] || exit 0

  echo "clovercon_hack: starting driver $MODULE"
  echo "home button combination: $cfg_clovercon_home_combination"
  echo "autofire: $cfg_clovercon_autofire"
  echo "autofire XY: $cfg_clovercon_autofire_xy"
  echo "autofire interval: $cfg_clovercon_autofire_interval"
  echo "famicom 2nd start workaround: $cfg_clovercon_fc_start"

  case "${CLV_BOARD_NAME}" in
    fp)
      # inverted c1/c2 detect lines
      MODULE_PARAMS="2,195,1,194"
    ;;
    dp-hvc)
      # no detect lines
      MODULE_PARAMS="1,-1,2,-1"
    ;;
    ep|dp-nes|dp-shvc|*)
      # regular setup w/ detect lines
      MODULE_PARAMS="1,195,2,194"
    ;;
  esac
  insmod "$mountpoint/lib/modules/$(uname -r)/extra/$MODULE.ko" \
         "module_params=$MODULE_PARAMS" \
         "home_combination=$cfg_clovercon_home_combination" \
         "autofire=$cfg_clovercon_autofire" \
         "autofire_xy=$cfg_clovercon_autofire_xy" \
         "autofire_interval=$cfg_clovercon_autofire_interval" \
         "fc_start=$cfg_clovercon_fc_start"
}

stop(){
  [ -z "$(lsmod | grep -F "$MODULE")" ] && exit 0
  echo "clovercon_hack: stopping driver $MODULE"
  modprobe -r "$MODULE"
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    stop
    start
  ;;
  *)
    echo "Usage: $(basename "$0") {start|stop|status|restart}"
    exit 1
esac
