#!/bin/sh

cd "`echo $* | sed -Ee 's#\\\\#/#g'`" || exit 1

download(){
  mkdir -p "`dirname "$2"`"
  [ -f "$2" ] || (wget "$1" -O "$2" || return 1)
}

download "https://github.com/DanTheMan827-Hakchi/font_remount.hmod/releases/download/1.2.0/font_remount-b5217ca.hmod" "mods/hmods/font_remount.hmod" || exit 1
download "https://cdn.discordapp.com/attachments/407270553183846400/427985727016402945/kernel.hmod" "mods/hmods/kernel.hmod"