#!/bin/sh
pwd="$(pwd)"
cd "`echo $* | sed -Ee 's#\\\\#/#g'`" || exit 1
downloadedFileListName="downloadedFiles.txt"
touch "$downloadedFileListName"
downloadedFiles="$(cat "$downloadedFileListName")"

download(){
  mkdir -p "`dirname "$2"`"
  ([ ! -f "$2" ] || [ "$(echo "$downloadedFiles" | grep -x "$2 $1")" == "" ]) && ($pwd/wget.exe "$1" -O "$2" 2>/dev/null || wget "$1" -O "$2" 2>/dev/null || return 1)
  echo "$2 $1" >> "$downloadedFileListName"
}

printf "" > "$downloadedFileListName"

download "https://hakchi.net/hakchi/hakchi-v1.0.4-121.hmod" "mods/hmods/hakchi.hmod" || exit 1
download "https://hakchi.net/hakchi/detached-fallback" "tools/arm/detached-fallback" || exit 1
download "https://github.com/TeamShinkansen/libwdi/releases/download/classic_driver_1/classic_driver.exe" "driver/classic_driver.exe" || exit 1