#!/bin/sh -e

start() {
	mcp-restarter &
}

stop() {
	killall mcp-restarter
}

case "$1" in
start)
	start
;;
stop)
	stop
;;
restart)
	stop
	start
;;
*)
	echo "mcp-restarter: Please use start, stop, or restart."
	exit 1
;;
esac
