#!/bin/sh

start() {
	nice remote-exec &
}

stop() {
	killall remote-exec
}

case "$1" in
start)
	start
;;
stop)
	stop
;;
restart)
	stop
	start
;;
*)
	echo "remote-exec: Please use start, stop, or restart."
	exit 1
;;
esac
